### ISSUE TITLE
Adding DAGMC to the openmc conda package.

### ISSUE THREAD

**Issue by shimwell** [conda-forge/openmc-feedstock#38]
It would be great to add DAGMC to this conda package.

I can see a couple of potential way to do it.

option 1 add DAGMC from a specific commit and compile it alongside openmc. It should be possible to get this working at the moment and I think something like this branch could be the way to go https://github.com/Shimwell/openmc-feedstock/tree/adding_dagmc_compile

option 2 add DAGMC as a conda package. Perhaps a nicer solution but we can't currently compile openmc when using dagmc installed via conda (open issue https://github.com/svalinn/DAGMC/issues/739 ). However, I've also drafted up a branch showing what this could look like https://github.com/Shimwell/openmc-feedstock/tree/adding_dagmc_conda

**Comment by paulromano** [comment]
Addressed in #42
