### ISSUE TITLE
Add MPI variants

### ISSUE THREAD

**Issue by paulromano** [conda-forge/openmc-feedstock#46]
Right now, the OpenMC package is not built with MPI support. We should add MPI variants (OpenMPI, MPICH) to ease downstream usage of OpenMC in cluster environments.

**Comment by shimwell** [comment]
I was also thinking the same thing :smile: I think we would add something like this to the ```conda_build_config.yaml```

```
mpi:
  - nompi
  - mpich
  - openmpi
```

Add to the top of the ```meta.yml``` file
```
# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}
```

Also add to the string section to something like this
```
  # add build string so packages can depend on
  # mpi or nompi and dagmc or nodagmc variants explicitly:
  # `openmc * mpi_mpich * nodagmc_*` for openmc with mpich and without dagmc
  # `openmc * mpi * nodagmc_*` for openmc with mpi and without dagmc
  # `openmc * nompi * nodagmc_*` for openmc without mpi and without dagmc
  # `openmc * mpi_mpich * dagmc_*` for openmc with mpich and with dagmc
  # `openmc * mpi * dagmc_*` for openmc with mpich and with dagmc
  # `openmc * nompi * dagmc_*` for openmc without mpi and with dagmc

  string: {{ mpi_prefix }}_{{ dagmc }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}
```

And change the ```build.sh``` to include some logic for the compiling similar to the [install scripts](https://github.com/openmc-dev/openmc/tree/develop/tools/ci) which I am a little less familiar with

If you like and if these changes look correct then I can get this started with a PR for these parts then perhaps team up for the build.sh part?

**Comment by shimwell** [comment]
In related news I am sure there are at least a couple of use also interested in adding Double Down and Embree options to the conda package

**Comment by shimwell** [comment]
I think the openmc conda install is currently broken and the error message appears to be mpi released

this is in a new conda enviroment and it appears even older versions of openmc are somehow impacted

![Screenshot from 2022-04-21 12-04-22](https://user-images.githubusercontent.com/8583900/164445069-0f6901e5-0d22-41dd-8fba-80280804ab3e.png)
