### ISSUE TITLE
Updated compile argument name for building with dagmc

### ISSUE THREAD

**Issue by shimwell** [conda-forge/openmc-feedstock#47]
### Comment:

Just noting that with the next release we will need to change the CONFIGURE_ARGS in build.sh from 

```-Ddagmc``` to ```-OPENMC_USE_DAGMC```

**Comment by kkiesling** [comment]
`-DOPENMC_USE_MPI` has also been implemented and the MPI build process will need updated with the next release too.

(also just making note)
